[project]
name = "velobike"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4==4.15.0",
    "customtkinter==6.0.0",
    "ddgs==9.14.4",
    "httpx==0.28.1",
    "openpyxl==3.1.5",
    "pandas==3.0.5",
    "pillow==12.3.0",
    "pyinstaller>=6.21.0",
    "pywin32>=312",
    "requests==2.34.2",
    "toml==0.10.2",
    "xlrd>=2.0.2",
]
